services:

  api:
    container_name: personal-ai-assistant-api

    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    restart: unless-stopped
