name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Sync dependencies
        run: uv sync

      - name: Ruff
        run: make lint

      - name: Tests
        run: make test
